local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()
local Window = library:CreateWindow("EGG HUNT (2023)")

local Main = Window:CreateFolder("Egg Hunt")

Main:Button("Collect All Egg",function()
fireclickdetector(game:GetService("Workspace")["Eggs"]["Basic Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Piano Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Owl Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Crystal Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Melon Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Disco Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Tower of Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Idol Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Jungle Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Cracked Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Humpty Dumpty Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Monkey Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Seal Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Spider Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Volcano Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Pirate Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Pencil Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Storm Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["UFO Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Penguin Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Cactus Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Candycane Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Canon Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Chocolate Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Clam Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Colorful Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Gem Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Hive Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Honey Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Ice Cream Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Abyss Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Dice Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Fancy Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Moon Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Mummy Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Pow Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Rocket Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Robin Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Strawberry Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Treasure Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Wish Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Pumpkin Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Angel Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Apple Egg"].ClickDetector)
    task.wait(0.7)
fireclickdetector(game:GetService("Workspace")["Eggs"]["Chocolate Chip Egg"].ClickDetector)
end)

Main:Label("Made By ExploitBacon",{
    TextSize = 20;
    TextColor = Color3.fromRGB(255,255,255);
    BgColor = Color3.fromRGB(69,69,69);
})
